### ISSUE TITLE
Unable to Enable NATS as Messaging Service in LuckPerms REST API

### ISSUE THREAD

**Issue by distribate** [LuckPerms/rest-api#19]
I'm encountering an issue with enabling NATS as the messaging service in the LuckPerms REST API. Despite correctly configuring the `LUCKPERMS_MESSAGING_SERVICE` environment variable to `nats` and providing the appropriate address, the service fails to recognize NATS.

**Environment Details:**
- **LuckPerms REST API Version:** [Specify version, e.g., `latest`]
- **Docker Compose Configuration:**
  ```yaml
  services:
    nats:
      container_name: nats
      image: nats:latest
      restart: unless-stopped
      ports:
        - "4222:4222"
      command: --T -VV
      networks:
        - shared-network

    luckperms-rest-api:
      image: ghcr.io/luckperms/rest-api
      environment:
        LUCKPERMS_STORAGE_METHOD: postgresql
        LUCKPERMS_DATA_ADDRESS: luckperms_db:5432
        LUCKPERMS_DATA_DATABASE: luckperms
        LUCKPERMS_DATA_USERNAME: user
        LUCKPERMS_DATA_PASSWORD: password
        LUCKPERMS_REST_HTTP_PORT: 4000
        LUCKPERMS_REST_AUTH: true
        LUCKPERMS_REST_AUTH_KEYS: ${SECRET_TOKEN}

        LUCKPERMS_MESSAGING_SERVICE: nats
        LUCKPERMS_MESSAGING_SERVICE_ADDRESS: nats:4222
      ports:
        - "4000:4000"
      networks:
        - shared-network
  networks:
    shared-network:
      driver: bridge
      
Actual Behavior: The service fails to recognize NATS, and the following warning appears in the logs:
```
Messaging Service was set to nats, but nats is not enabled!
Messaging service 'nats' not recognised.
```

Please let me know if any additional details are needed. Thank you for your support!

**Comment by lucko** [comment]
Admittedly this is not in the documentation (oops - NATS was a pull requested addon, I guess the wiki updates were missed)

However, the NATS configuration is largely the same format as for redis and rabbitmq. here's an example from the tests:

https://github.com/LuckPerms/LuckPerms/blob/0fef481d480737528491fc0b3b8487eb1612f955/standalone/src/test/java/me/lucko/luckperms/standalone/MessagingIntegrationTest.java#L287-L289

I think if you set as follows, it should work

```yaml
services:
  luckperms-rest-api:
    image: ghcr.io/luckperms/rest-api
    environment:
      LUCKPERMS_MESSAGING_SERVICE: nats
      LUCKPERMS_NATS_ENABLED: "true"
      LUCKPERMS_NATS_ADDRESS: "nats:4222"
```
